// src/services/privacy/privacyService.ts
/**
 * Privacy Service - Manages user anonymity and data controls
 * Implements Rule 1: Privacy First — Never compromise anonymity
 * Implements Rule 6: POPIA compliant
 */

import * as SecureStore from 'expo-secure-store';
import * as Crypto from 'expo-crypto';

// Storage keys
const ANONYMOUS_ID_KEY = 'pshad_anonymous_id';
const ANONYMOUS_ID_CREATED_KEY = 'pshad_anonymous_id_created';

// ---- Anonymous ID Management ----

/**
 * Get or create anonymous device ID
 * This ID is:
 * - Persistent across app restarts
 * - Not linked to any personal information
 * - Stored securely on device only
 * - Can be regenerated by user
 */
export async function getAnonymousId(): Promise<string> {
  try {
    // Try to get existing ID
    const existingId = await SecureStore.getItemAsync(ANONYMOUS_ID_KEY);
    
    if (existingId) {
      return existingId;
    }
    
    // Generate new ID if none exists
    return await generateNewAnonymousId();
  } catch (error) {
    console.error('[PrivacyService] Error getting anonymous ID:', error);
    // Return a temporary session ID if secure store fails
    return generateTemporaryId();
  }
}

/**
 * Generate and store a new anonymous ID
 * Call this when user wants to "reset" their anonymous identity
 */
export async function generateNewAnonymousId(): Promise<string> {
  try {
    // Generate cryptographically secure random ID
    const randomBytes = await Crypto.getRandomBytesAsync(16);
    const hexString = Array.from(randomBytes)
      .map(b => b.toString(16).padStart(2, '0'))
      .join('');
    
    // Format: anon_XXXX...XXXX (32 hex chars)
    const newId = `anon_${hexString}`;
    
    // Store securely
    await SecureStore.setItemAsync(ANONYMOUS_ID_KEY, newId);
    await SecureStore.setItemAsync(ANONYMOUS_ID_CREATED_KEY, new Date().toISOString());
    
    console.log('[PrivacyService] New anonymous ID generated');
    return newId;
  } catch (error) {
    console.error('[PrivacyService] Error generating anonymous ID:', error);
    return generateTemporaryId();
  }
}

/**
 * Get creation date of anonymous ID
 */
export async function getAnonymousIdCreatedDate(): Promise<string | null> {
  try {
    return await SecureStore.getItemAsync(ANONYMOUS_ID_CREATED_KEY);
  } catch {
    return null;
  }
}

/**
 * Generate temporary ID (fallback when secure store unavailable)
 */
function generateTemporaryId(): string {
  const timestamp = Date.now().toString(36);
  const random = Math.random().toString(36).substring(2, 10);
  return `temp_${timestamp}_${random}`;
}

/**
 * Format anonymous ID for display (truncated)
 * Shows first 8 and last 4 characters
 */
export function formatAnonymousId(id: string): string {
  if (id.length <= 16) return id;
  
  const prefix = id.substring(0, 12);
  const suffix = id.substring(id.length - 4);
  return `${prefix}...${suffix}`;
}

// ---- Data Collection Info ----

export interface DataCollectionItem {
  id: string;
  label: string;
  description: string;
  isCollected: boolean;
  icon: string;
}

/**
 * Get list of data collection practices
 * Transparent disclosure for POPIA compliance
 */
export function getDataCollectionInfo(): DataCollectionItem[] {
  return [
    {
      id: 'anonymous_tips',
      label: 'Anonymous Tips',
      description: 'Your tip reports with no personal identifiers',
      isCollected: true,
      icon: 'document-text-outline',
    },
    {
      id: 'notification_prefs',
      label: 'Notification Preferences',
      description: 'Your push notification settings',
      isCollected: true,
      icon: 'notifications-outline',
    },
    {
      id: 'fuzzed_location',
      label: 'Approximate Location',
      description: 'Only when you choose to share, rounded to ~100m',
      isCollected: true,
      icon: 'location-outline',
    },
    {
      id: 'name',
      label: 'Name',
      description: 'We never ask for or store your name',
      isCollected: false,
      icon: 'person-outline',
    },
    {
      id: 'email',
      label: 'Email Address',
      description: 'No account or email required',
      isCollected: false,
      icon: 'mail-outline',
    },
    {
      id: 'phone',
      label: 'Phone Number',
      description: 'We never collect phone numbers',
      isCollected: false,
      icon: 'call-outline',
    },
    {
      id: 'device_id',
      label: 'Device Identifiers',
      description: 'No IMEI, MAC address, or device IDs',
      isCollected: false,
      icon: 'phone-portrait-outline',
    },
    {
      id: 'contacts',
      label: 'Contacts',
      description: 'We never access your contacts',
      isCollected: false,
      icon: 'people-outline',
    },
  ];
}

// ---- Data Controls ----

/**
 * Clear all local app data
 * This removes:
 * - Anonymous ID (will regenerate)
 * - Push notification token
 * - Any cached data
 */
export async function clearAllLocalData(): Promise<boolean> {
  try {
    // Clear anonymous ID
    await SecureStore.deleteItemAsync(ANONYMOUS_ID_KEY);
    await SecureStore.deleteItemAsync(ANONYMOUS_ID_CREATED_KEY);
    
    // Clear push token
    await SecureStore.deleteItemAsync('pshad_push_token');
    
    console.log('[PrivacyService] All local data cleared');
    return true;
  } catch (error) {
    console.error('[PrivacyService] Error clearing data:', error);
    return false;
  }
}

/**
 * Get privacy tips for user education
 */
export interface PrivacyTip {
  id: string;
  icon: string;
  title: string;
  description: string;
}

export function getPrivacyTips(): PrivacyTip[] {
  return [
    {
      id: 'anonymous',
      icon: 'shield-checkmark',
      title: 'Completely Anonymous',
      description: 'Your tips cannot be traced back to you. We use a random ID that is not linked to your identity.',
    },
    {
      id: 'encrypted',
      icon: 'lock-closed',
      title: 'Encrypted Storage',
      description: 'Your anonymous ID is stored securely on your device using encryption.',
    },
    {
      id: 'no_account',
      icon: 'person-remove',
      title: 'No Account Required',
      description: 'You never need to create an account, sign in, or provide any personal details.',
    },
    {
      id: 'location_control',
      icon: 'navigate',
      title: 'Location is Optional',
      description: 'You choose when to share location. When shared, it\'s rounded to protect your exact position.',
    },
    {
      id: 'popia',
      icon: 'ribbon',
      title: 'POPIA Compliant',
      description: 'We comply with South Africa\'s Protection of Personal Information Act.',
    },
  ];
}