/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/apply-journalist`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(stack)'}/incidents` | `/incidents`; params?: Router.UnknownInputParams; } | { pathname: `${'/(stack)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(stack)'}/live` | `/live`; params?: Router.UnknownInputParams; } | { pathname: `${'/(stack)'}/map` | `/map`; params?: Router.UnknownInputParams; } | { pathname: `${'/(stack)'}/news` | `/news`; params?: Router.UnknownInputParams; } | { pathname: `${'/(stack)'}/opportunities` | `/opportunities`; params?: Router.UnknownInputParams; } | { pathname: `${'/(stack)'}/safety` | `/safety`; params?: Router.UnknownInputParams; } | { pathname: `${'/(stack)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `${'/(stack)'}/article/[id]` | `/article/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/apply-journalist`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(stack)'}/incidents` | `/incidents`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(stack)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(stack)'}/live` | `/live`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(stack)'}/map` | `/map`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(stack)'}/news` | `/news`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(stack)'}/opportunities` | `/opportunities`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(stack)'}/safety` | `/safety`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(stack)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } } | { pathname: `${'/(stack)'}/article/[id]` | `/article/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/apply-journalist${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(stack)'}/incidents${`?${string}` | `#${string}` | ''}` | `/incidents${`?${string}` | `#${string}` | ''}` | `${'/(stack)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(stack)'}/live${`?${string}` | `#${string}` | ''}` | `/live${`?${string}` | `#${string}` | ''}` | `${'/(stack)'}/map${`?${string}` | `#${string}` | ''}` | `/map${`?${string}` | `#${string}` | ''}` | `${'/(stack)'}/news${`?${string}` | `#${string}` | ''}` | `/news${`?${string}` | `#${string}` | ''}` | `${'/(stack)'}/opportunities${`?${string}` | `#${string}` | ''}` | `/opportunities${`?${string}` | `#${string}` | ''}` | `${'/(stack)'}/safety${`?${string}` | `#${string}` | ''}` | `/safety${`?${string}` | `#${string}` | ''}` | `${'/(stack)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/apply-journalist`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(stack)'}/incidents` | `/incidents`; params?: Router.UnknownInputParams; } | { pathname: `${'/(stack)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(stack)'}/live` | `/live`; params?: Router.UnknownInputParams; } | { pathname: `${'/(stack)'}/map` | `/map`; params?: Router.UnknownInputParams; } | { pathname: `${'/(stack)'}/news` | `/news`; params?: Router.UnknownInputParams; } | { pathname: `${'/(stack)'}/opportunities` | `/opportunities`; params?: Router.UnknownInputParams; } | { pathname: `${'/(stack)'}/safety` | `/safety`; params?: Router.UnknownInputParams; } | { pathname: `${'/(stack)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | `${'/(stack)'}/article/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/article/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `${'/(stack)'}/article/[id]` | `/article/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
